import type { Metadata } from "next";
import { Poppins, Montserrat } from "next/font/google"; // Importando Poppins e Montserrat
import "./globals.css";

// Configuração da fonte Poppins (padrão)
const poppins = Poppins({
  weight: ["400", "500", "600", "700"], // Pesos da fonte
  subsets: ["latin"], // Subconjuntos de caracteres
  variable: "--font-poppins", // Variável CSS para a fonte
});

// Configuração da fonte Montserrat (apenas para o h1)
const montserrat = Montserrat({
  weight: ["400", "500", "600", "700"], // Pesos da fonte
  subsets: ["latin"], // Subconjuntos de caracteres
  variable: "--font-montserrat", // Variável CSS para a fonte
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      {/* Aplicando Poppins como fonte padrão no body */}
      <body className={poppins.className}>
        {children}
      </body>
    </html>
  );
}
