import type { Metadata } from "next";
import { Barlow } from "next/font/google"; 
import "./globals.css";

const barlow = Barlow({
  weight: ["400", "500", "600", "700"], 
  subsets: ["latin"], 
  variable: "--font-poppins", 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      {/* aplicando a fonte Poppins ao body */}
      <body className={barlow.className}>
        {children}
      </body>
    </html>
  );
}
