import type { Metadata } from "next";
import { Barlow } from "next/font/google"; // Importando a fonte Poppins
import "./globals.css";

// Configuração da fonte Poppins
const barlow = Barlow({
  weight: ["400", "500", "600", "700"], // Defina os pesos que você deseja usar
  subsets: ["latin"], // Subconjuntos de caracteres
  variable: "--font-poppins", // Variável CSS para usar a fonte
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      {/* Aplicando a fonte Poppins ao body */}
      <body className={barlow.className}>
        {children}
      </body>
    </html>
  );
}
